version: "3"

services:
  snpm:
    command: "npm start"
    image: node:10.1.0-alpine
    working_dir: /opt/app
    environment:
      - REGISTRY_PORT=3000
      - REGISTRY_URL=http://localhost
    volumes:
      - ./:/opt/app
    ports:
      - "3000:3000"