version: "3"

services:
  snpm:
    command: "npm start"
    image: node:9.4.0-alpine
    working_dir: /opt/app
    environment:
      - REGISTRY_PORT=3000
    volumes:
      - ./:/opt/app
    ports:
      - "3000:3000"